- README.md
A small fix to change to drop the "a" in "solving a many interview questions".
> Fix typo in Study Guide section

- README.md
> Add Dyn DDoS attack link

- README.md
Under CDN section, change JSS to JS
> Fix typo JSS -> JS

- README.md
I think some developers get confused between PUT & PATCH. [This Laracasts comment](https://laracasts.com/discuss/channels/general-discussion/whats-the-differences-between-put-and-patch?page=1) hopes to provide a clear distinction between the two.
> Explain difference between PUT & PATCH

- CONTRIBUTING.md
Add credits section.  Remove currently non-existent AUTHORS.md.  Fix maintainer copy/paste error.
> Update translations section in contributing guidelines

- README-zh-Hant.md
At your request (#60), we have created a new branch to squash these commits. Now there's only one commit in the history. 😜
> zh-cn: Add Simplified Chinese translation v1.0

- README.md
Move the list of completed and in-progress translations to the top of the README.  Add Translate link to the Contributing section.
> Update translation links

- README.md
Fixed letter case for title **layer 7 load balancing**
> Fix lowercase typo in Layer 7 load balancing title

- solutions/object_oriented_design/parking_lot/parking_lot.ipynb
> Init spot_size member in parking lot exercise

- README.md
> Mention policy for adding new blogs to Company engineering blogs section

- solutions/system_design/scaling_aws/README.md
thank you for an awesome repo. I think I found a minor typo and thought I would correct it.
> Fix typo: considering -> consider in scaling AWS solution

- solutions/system_design/query_cache/README.md
- solutions/system_design/scaling_aws/README.md
- solutions/system_design/social_graph/README.md
- solutions/system_design/web_crawler/README.md
#master-slave doesn't go anywhere, the relevant link is #master-slave-replication.
> Update master-slave section anchor

- solutions/object_oriented_design/deck_of_cards/deck_of_cards.py
> Add missing self variables to Deck of Cards solution

- solutions/system_design/social_graph/social_graph_snippets.py
https://docs.python.org/3/library/collections.html#deque-objects  Discovered via #93
> Add deque import to Social Graph solution

- solutions/object_oriented_design/parking_lot/parking_lot.py
The class name is required in this context.  Discovered via #93
> Change LARGE to VehicleSize.LARGE in parking lot solution

- README-zh-TW.md
This line is to express an asterisk comment,
space will be parsed into list tag
> zh-TW: Fix comment format

- solutions/object_oriented_design/parking_lot/parking_lot.py
__levels__ is an _undefined name_ in this context (see #93) so replace it with __self.levels__ which is defined a few lines above.
> Adding missing self variable

- README-zh-Hans.md
> zh-Hans: Fix typo

- solutions/system_design/social_graph/social_graph_snippets.py
* Fixes #148
* Enables #93
* Replaces #162
> Fix #148: Add State(Enum) to social_graph_snippets.py

- solutions/object_oriented_design/call_center/call_center.ipynb
The link to the GitHub page was incorrect. Fixed it.
> Fix broken URL

- solutions/object_oriented_design/deck_of_cards/deck_of_cards.ipynb
- solutions/object_oriented_design/hash_table/hash_map.ipynb
- solutions/object_oriented_design/lru_cache/lru_cache.ipynb
- solutions/object_oriented_design/online_chat/online_chat.ipynb
- solutions/object_oriented_design/parking_lot/parking_lot.ipynb
> Resolve #195: Fix broken GitHub URLs

- README.md
Align title in `System design interview questions with solutions` table with the subsequent section.
> Update Twitter/Facebook exercise description

- README.md
"document-store" -> "document store"
> Update document-store to document store

- solutions/system_design/pastebin/README.md
I will come back around a bit later and make this change for all code snippets throughout.
> Enable Python syntax highlighting in Pastebin sample code

- README-ja.md
- README-zh-Hans.md
- README-zh-TW.md
- README.md
- solutions/system_design/mint/README.md
- solutions/system_design/pastebin/README.md
- solutions/system_design/query_cache/README.md
- solutions/system_design/sales_rank/README.md
- solutions/system_design/social_graph/README.md
- solutions/system_design/web_crawler/README.md
Quick run through all embedded python snippets to enable syntax highlighting.
There are possibly other formats to be enabled, which I'll come back to later.
Hope this helps!
> Enable syntax highlighting in all python code snippets

- README-zh-Hans.md
- solutions/system_design/pastebin/README-zh-Hans.md
- solutions/system_design/pastebin/README.md
> zh-Hans: Translate Pastebin solution

- README-ja.md
- The original translation is explanation of the feature of Anki app (spaced repetition), rather than the flashcard decks.
> ja: Fix translation in Anki flashcards section

- README.md
Hi,
I have found a very good API Security checklist which has more than 13k ⭐️ on github, it is worth to be added to our Security section.
> Add API security checklist inside Security section

- README-zh-Hans.md
- solutions/system_design/mint/README.md
- solutions/system_design/pastebin/README.md
- solutions/system_design/query_cache/README.md
- solutions/system_design/sales_rank/README.md
- solutions/system_design/scaling_aws/README.md
- solutions/system_design/social_graph/README.md
- solutions/system_design/twitter/README.md
- solutions/system_design/web_crawler/README.md
This reverts commit 301b9d88e4aed1c34b3275301f18b14957c38c91.
#374 overwrote the English version of the solutions
> Revert "zh-cn: Sync with upstream to keep it up-to-date (#374)"

- README.md
Upgrading "Scaling up to your first 10 million users" video link to https://www.youtube.com/watch?v=kKjm4ehYiMs which is the latest talk as of today
> Update "Scaling up to your first 10 million users" link

- README.md
…ition of AP under CAP theorem portion.
Updated the wordings as per issue #164  - Confusing word play in the definition of AP under CAP theorem portion.
> Resolve #164 - Fix phrasing with availability and partition tolerance

- solutions/system_design/twitter/README.md
Made a small change to explain the logic behind the 4,000 search requests per second.
> Update design Twitter back-of-the-envelope calculations

- solutions/system_design/twitter/README.md
- solutions/system_design/web_crawler/README.md
As pertains to issue #344 with one extra typo spotted during correction.
> Fix typos in Twitter and web crawler exercises

- README.md
> Fix #313: Clarify availability patterns

- README.md
I feel that [this](https://www.youtube.com/watch?v=k-Yaq8AHlFA) short video explains the CAP theorem really well.
> Add CAP theorem video

- README.md
Added Amazon AWS public docs link for better understanding of latency based and geo-location based routing.
> Add links for latency based and geolocation based routing

- README.md
It is clearer to say that a user receives data "from" a data center then it is to say that a user receives data "at" a data center.
> Clarify CDN advantages

- README.md
fixes https://github.com/donnemartin/system-design-primer/issues/281
> Resolve #281: Add design stock exchange links

- .github/PULL_REQUEST_TEMPLATE.md
Fix TRANSLATIONS.md to absolute path
> Fix translations link in PR template

- README.md
> Fix Celery url

- README-ja.md
- README-zh-Hans.md
- README-zh-TW.md
- README.md
This PR fixes Link to Memchached architecture and solves [#593](https://github.com/donnemartin/system-design-primer/issues/593)
> Fix memcache architecture URL

- README.md
> Replace broken weighted round robin link (#650)

- README.md
> Update latency vs throughput blog link

- README.md
> Fix top k requests link

- README.md
Linking to Wayback Machine since it seems the domain expired?
> Fix Scalability Article links

- README-ja.md
- README-zh-Hans.md
- README-zh-TW.md
- README.md
Update all lecloud.net links to the web archive since the lecloud.net website does not exist anymore
Used same links as in https://github.com/donnemartin/system-design-primer/blob/master/README.md?plain=1#L392-L398
> Update all lecloud.net links
