README.md
Small typo in the Remote Procedure Call section.
s/definied/defined
=> Fix typo in RPC section

README.md, solutions/system_design/mint/README.md, solutions/system_design/pastebin/README.md, solutions/system_design/query_cache/README.md, solutions/system_design/sales_rank/README.md, solutions/system_design/social_graph/README.md, solutions/system_design/twitter/README.md, solutions/system_design/web_crawler/README.md
Changed the links in the main README and in the readme files inside solutions/ to address #6.
Skipped the links from the files inside solutions/ to the main readme, so that they won't break if the directory structure change.
=> Fix #6: Migrate links from exercises/solutions to use internal links

README.md
As the variable `key` is not defined, the example could generate a little of confusion in my opinion.
If we don't want to add more complexity using `format()`, we should be also able to just do `key = "user.{user_id}`.
=> Declare variable key in the get_user example

README.md
* Add sources and further reading to HTTP section
* Fix caps and punctuation in RPC section
* Change large scale -> large-scale in intro
=> Polish up HTTP, RPC, and intro sections

README.md
I think that the description for AP should be changed. It currently says that the most recent version of the data might not be the latest. 
The explanation of Consistency uses the same word, recent. 
I have changed AP to qualify 'recent' as being the most recent data available on the node
=> Change AP wording for clarity

solutions/system_design/pastebin/README.md
This should make it clear that the code the developer writes for the reduce steps indeed gets an iterable of values, not only a single value.
That's how the [luigi mapreduce framework](https://github.com/spotify/luigi/blob/710e7238406a9843945c74d53f5524a6284194f0/examples/wordcount_hadoop.py#L84) is designed at least.
=> Fix reducer argument in pastebin exercise

solutions/system_design/twitter/README.md
```
tweet n+2                   tweet n+1                   tweet n
| 8 bytes   8 bytes  1 byte | 8 bytes   8 bytes  1 byte | 8 bytes   7 bytes  1 byte |
| tweet_id  user_id  meta   | tweet_id  user_id  meta   | tweet_id  user_id  meta   |
```
should the 7 be 8?
=> Correct Redis list structure in Twitter solution

solutions/object_oriented_design/call_center/call_center.py, solutions/object_oriented_design/deck_of_cards/deck_of_cards.py, solutions/object_oriented_design/lru_cache/lru_cache.py, solutions/object_oriented_design/online_chat/online_chat.py, solutions/object_oriented_design/parking_lot/parking_lot.py, solutions/system_design/social_graph/social_graph_snippets.py, solutions/system_design/web_crawler/web_crawler_snippets.py
`raise NotImplementedError('Please replace this line with your code...')` signals to the user where they need to put their code.
This approach enables the codebase to be tested with lint tools like flake8, pyflakes, pylint, etc.
=> Convert all .py files to be valid Python

solutions/object_oriented_design/lru_cache/lru_cache.py, solutions/system_design/query_cache/query_cache_snippets.py
Without these colons, these lines are syntax errors.  Discovered via #93
=> Add missing colons to class methods

solutions/object_oriented_design/online_chat/online_chat.py, solutions/system_design/mint/mint_snippets.py
Resolve the _undefined name_ __Enum__ in two files by importing it from [__enum__](https://docs.python.org/3/library/enum.html).  Also fix a Syntax Error.
flake8 testing of https://github.com/donnemartin/system-design-primer on Python 3.6
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./solutions/object_oriented_design/online_chat/online_chat.py:98:21: F821 undefined name 'Enum'
class RequestStatus(Enum):
^
./solutions/system_design/mint/mint_snippets.py:3:25: F821 undefined name 'Enum'
class DefaultCategories(Enum):
^
2    F821 undefined name 'Enum'
2
```
=> Add missing enum imports

solutions/system_design/mint/mint_mapreduce.py
In the current code, __seller__ is an unused variable and __category__ is an undefined name (see #93).
Given that the class is __SpendingByCategory__, this PR advocates changing seller —> category.
=> Change variable seller to category in Mint solution

README.md
Also replaced the "performance issues" link for mysql version 5.7.
=> Replace broken SQL tuning links

README.md
Previous link would cause download to be an incorrectly formatted apkg file.  
Changed the links to absolute links to the files instead of relative links.
See Issue #126.
=> Fix #126: Update link to Anki decks

README.md
The cassandra architecture link was pointing to an old, archived version of cassandra. Since they have the same document but in a new version, I found it fair to update it. I don't know if the correct would be changing only english or all four languages versions, I am only updating the english one in this commit/PR. The link itself appear twice per readme file. A simple `sed -i 's/\/archived\/cassandra\/2\.0\/cassandra\/architecture\/architectureIntro\_c/\/cassandra\/3\.0\/cassandra\/architecture\/architectureIntro/g' README*` can make it for all.
=> Update Cassandra architecture links

README.md, solutions/system_design/mint/README.md
=> Resolve #214: Add reference links to message queues section

README-ja.md, README-zh-Hans.md, README-zh-TW.md, README.md
@donnemartin 
Fixes https://github.com/donnemartin/system-design-primer/issues/228
=> Fix #228: Address mutex latency discrepancy

README.md
`organized by` is more correct than `organized in either`
=> Fix grammar in document store section

solutions/system_design/scaling_aws/README.md
There is no anchor for #sql on the README page, so I changed it to the most related topic #relational-database-management-system-rdbms
=> Fix broken SQL link in Scaling AWS exercise

README.md
Points:
- 9s of availability with example of 99.9 and 99.99 percentage
- Difference in availability with components in sequence or parallel
=> Add availability in numbers section

README-ja.md
- Consul, Etcd, and Zookeeper don’t find each other, but the services in those systems do.
- "integrity" means "完全性" in Japanese. "統一性" isn’t used in this kind of context.
- Make the translation more fluent ("しばしば" for "often", and "そして" for "and" are too literal).
=> ja: Fix translation in Service Discovery section

README-zh-Hans.md
change CN translation to make it more accurate. SQL tuning -> Blob
=> change CN translation to make it more accurate

solutions/object_oriented_design/call_center/call_center.py
__flake8 . --count --exit-zero --max-complexity=10 --statistics__
```
./solutions/object_oriented_design/call_center/call_center.py:69:9:
F901 'raise NotImplemented' should be 'raise NotImplementedError'
```
https://docs.python.org/3/library/exceptions.html#NotImplementedError
=> raise NotImplemented —> raise NotImplementedError

README.md
Change URLs from [http://g33kinfo.com/info/archives/2657](http://g33kinfo.com/info/archives/2657) (broken) to [https://www.g33kinfo.com/info/2010/02/round-robin-vs-weighted-round-robin-lb](https://www.g33kinfo.com/info/2010/02/round-robin-vs-weighted-round-robin-lb)
=> Fix broken 'round robin' links

generate-epub.sh
Fixes https://github.com/donnemartin/system-design-primer/issues/339
@donnemartin @Skn0tt Please check
=> Check dependencies in Ebook gen script

solutions/system_design/web_crawler/README.md
I believe there's a typo in here and it should say "federation" as opposed to "replication" as replication does not solve the problem of data size and request load.
=> Fix typo: Change replication to federation

solutions/system_design/pastebin/README.md
Making a column a primary key enforces uniqueness, and the db usually does so by creating a unique clustered index. So, you don't need a second index.
=> Remove redundant SQL index in Pastebin exercise

README.md
In several parts of the article there is a "disk" as a permanent storage medium. In the changed paragraph there is "SSD" (flash disk), and in the opposition to it "disk", although it is about HDD (magnetic disk).
=> Change disk to HDD for clarity

README.md
Fix for #475. The paragraph talking about wide column store also has the dead HBase link. It started redirecting to something different earlier this year.
The [new link](https://www.edureka.co/blog/hbase-architecture/) goes to a relevant HBase architecture page and contains the same info as the original page from before.
=> Update broken HBase architecture link

README.md
The current URL: `https://en.wikipedia.org/wiki/Cache_algorithms#Least_Recently_Used` doesn't point to LRU section
=> Fix LRU cache link

README-ja.md, README-zh-Hans.md, README-zh-TW.md, README.md
As of today, the newest article of https://githubengineering.com and https://github.blog/category/engineering were from 2019/03/05 and 2021/10/06 respectively. Not sure what happened to https://githubengineering.com , but https://github.blog/category/engineering seems to be more up to date.
| https://githubengineering.com | https://github.blog/category/engineering |
| --- | --- |
| <img width="969" alt="image" src="https://user-images.githubusercontent.com/12410942/136699074-a45047ca-c9c9-449f-a2ca-25e30adddc6e.png"> | <img width="990" alt="image" src="https://user-images.githubusercontent.com/12410942/136699084-125548b6-28df-4e49-b80b-c01a34c48666.png"> |
=> Update GitHub Engineer Blog link

README.md
Now, instead of hyperlinks landing to a routing index page, they route to relevant web pages. This issue might have been caused due to source website moving index page sections to separate web pages.
=> Fix DNS routing hyperlinks

README-ja.md, README-zh-Hans.md, README-zh-TW.md, README.md
Added popular Payment processing, Stripe engineering blog reference in Company engineering blogs section.
=> Add Stripe engineering blog
